#!/bin/bash
printf "%o\n" $(($((5#$(echo $WATER | tr water 01234))) + $((5#$(echo $STIR | tr stir. 01234))))) | tr 01234567 bestchol # command to transform 2 vars and then convert them to base 5 then add them together and transform to base 8 type then print specifier for octal
