#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine

apt-get update -y
apt-get install nginx -y
ufw allow 80
sh -c 'echo "Hello World!" > /var/www/html/index.html'
service nginx restart
