#!/usr/bin/env bash
# Bash script that configures a Ubuntu server
# to have a custom 404 page that contains the string

apt-get update -y
apt-get install nginx -y
ufw allow 80
sh -c 'echo "Hello World!" > /var/www/html/index.html'
echo -e "Ceci n'est pas une page" | sudo tee /var/www/html/my_404.html
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/ permanent;' /etc/nginx/sites-available/default
sed -i '/listen 80 default_server/a error_page 404 /404.html;\nlocation = /404.html {\n
    root /var/www/html/my_404.html;\n    internal;\n}' /etc/nginx/sites-available/default

service nginx restart
