#!/usr/bin/env bash
# Bash script that Configures Nginx so that its HTTP response contains a custom header

sed -i '/server_name _;/a \\n\
        add_header X-Served-By $(hostname);\n\'
        /etc/nginx/sites-available/default

service nginx restart
