#!/usr/bin/env bash
# Bash script that:-
# - Creates the file /var/run/myscript.pid containing its PID
# - Displays To infinity and beyond indefinitely
# - Displays I hate the kill command when receiving a SIGTERM signal
# - Displays Y U no love me?! when receiving a SIGINT signal
# - Deletes the file /var/run/myscript.pid and terminates
#+  itself when receiving a SIGQUIT or SIGTERM signal

pid_file="/var/run/myscript.pid"

terminate(){
	rm "$pid_file"
}

echo "$$" > "$pid_file"

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I hate the kill command" && terminate' SIGTERM
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'terminator' SIGQUIT
done
