#!/usr/bin/env bash
# Write a Bash script that displays numbers from 1 to 100 using FizzBuzz

for i in {1..100}
do
    if [ $((i % 15)) -eq 0 ]; then
        echo "FizzBuzz"
    elif [ $((i % 3)) -eq 0 ]; then
       	echo "Fizz"
    elif [ $((i % 5)) -eq 0 ]; then
        echo "Buzz"
	else
		echo "$i"
	fi
    i=$((i + 1))
done
