#!/usr/bin/env bash
# Displays the contents of the file `/etc/passwd'
#+ using the while loop + IFS.

while IFS=: read -r username password uid gid gecos home shell
do
  echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $gecos"
done < "/etc/passwd"
