#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements

#+ localhost resolves to 127.0.0.2
#+ facebook.com resolves to 8.8.8.8.
echo "127.0.0.2    localhost" > ~/hosts.new1
echo "8.8.8.8    facebook.com" >> ~/hosts.new1
cp -f ~/hosts.new1 /etc/hosts
