#!/usr/bin/env bash
# Script to Run Nginx as Nginx
pkill apache2
chown nginx /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
