#!/usr/bin/env bash
# Script to Run Nginx as Nginx
echo "user nginx;" | sudo tee -a /etc/nginx/nginx.conf > /dev/null
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
